import { internalMutation } from "./_generated/server";

const destinations = [
  {
    name: "Boracay",
    slug: "boracay",
    description:
      "World-famous white sand beach with crystal-clear turquoise waters. Station 1 has the widest stretch of powdery sand, while D'Mall offers vibrant nightlife and dining.",
    region: "Visayas",
    province: "Aklan",
    latitude: 11.9674,
    longitude: 121.9247,
    categories: ["Beach", "Island Hopping"],
    tags: ["nightlife", "water-sports", "family-friendly", "romantic"],
    budgetMin: 3000,
    budgetMax: 15000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [
      { name: "Ati-Atihan", month: 1, description: "Festival honoring the Santo Niño with street dancing" },
    ],
  },
  {
    name: "El Nido",
    slug: "el-nido",
    description:
      "Stunning limestone karst cliffs, hidden lagoons, and pristine beaches. Island hopping tours A through D reveal secret coves, snorkeling spots, and turquoise waters.",
    region: "Luzon",
    province: "Palawan",
    latitude: 11.1784,
    longitude: 119.3932,
    categories: ["Beach", "Island Hopping"],
    tags: ["adventure", "snorkeling", "romantic", "nature"],
    budgetMin: 4000,
    budgetMax: 20000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Siargao",
    slug: "siargao",
    description:
      "The surfing capital of the Philippines. Cloud 9 is a world-class wave, but the island also offers lagoons, rock pools, mangrove forests, and a laid-back island vibe.",
    region: "Mindanao",
    province: "Surigao del Norte",
    latitude: 9.8482,
    longitude: 126.0458,
    categories: ["Beach", "Island Hopping"],
    tags: ["surfing", "adventure", "budget-friendly", "nature"],
    budgetMin: 2500,
    budgetMax: 12000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Dry season (Mar-Oct)",
    festivals: [],
  },
  {
    name: "Banaue Rice Terraces",
    slug: "banaue-rice-terraces",
    description:
      "2,000-year-old hand-carved rice terraces often called the Eighth Wonder of the World. Hike through Batad amphitheater terraces and Tappiya Falls.",
    region: "Luzon",
    province: "Ifugao",
    latitude: 16.9141,
    longitude: 121.0544,
    categories: ["Mountain", "Historical"],
    tags: ["hiking", "cultural", "photography", "heritage"],
    budgetMin: 2000,
    budgetMax: 6000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Feb-Jun)",
    festivals: [
      { name: "Imbayah Festival", month: 4, description: "Celebration of Ifugao culture and rice harvest" },
    ],
  },
  {
    name: "Coron",
    slug: "coron",
    description:
      "Japanese WWII shipwrecks, pristine lakes, and coral reefs make Coron a top diving and snorkeling destination. Kayangan Lake is often called the cleanest lake in the Philippines.",
    region: "Luzon",
    province: "Palawan",
    latitude: 11.9986,
    longitude: 120.2043,
    categories: ["Beach", "Island Hopping"],
    tags: ["diving", "snorkeling", "adventure", "photography"],
    budgetMin: 3500,
    budgetMax: 18000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Intramuros",
    slug: "intramuros",
    description:
      "The historic walled city of Manila, built during Spanish colonial period. Explore Fort Santiago, Manila Cathedral, and San Agustin Church — a UNESCO World Heritage Site.",
    region: "NCR",
    province: "Metro Manila",
    latitude: 14.5896,
    longitude: 120.9747,
    categories: ["Historical", "City"],
    tags: ["cultural", "heritage", "walking-tour", "photography"],
    budgetMin: 500,
    budgetMax: 3000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Chocolate Hills",
    slug: "chocolate-hills",
    description:
      "Over 1,200 perfectly cone-shaped hills that turn brown during the dry season. A geological marvel in the heart of Bohol, best viewed from the observation deck in Carmen.",
    region: "Visayas",
    province: "Bohol",
    latitude: 9.7964,
    longitude: 124.0672,
    categories: ["Mountain"],
    tags: ["nature", "photography", "family-friendly", "unique"],
    budgetMin: 1500,
    budgetMax: 5000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Mar-May)",
    festivals: [
      { name: "Sandugo Festival", month: 7, description: "Celebrates the blood compact between Datu Sikatuna and Legazpi" },
    ],
  },
  {
    name: "Kawasan Falls",
    slug: "kawasan-falls",
    description:
      "A stunning multi-tiered waterfall with turquoise waters perfect for canyoneering. The adventure includes cliff jumping, swimming through canyons, and bamboo rafting.",
    region: "Visayas",
    province: "Cebu",
    latitude: 9.8088,
    longitude: 123.3656,
    categories: ["Waterfall"],
    tags: ["adventure", "canyoneering", "swimming", "nature"],
    budgetMin: 1500,
    budgetMax: 4000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Year-round",
    festivals: [],
  },
  {
    name: "Vigan",
    slug: "vigan",
    description:
      "UNESCO World Heritage city with the best-preserved example of a Spanish colonial town in Asia. Walk down Calle Crisologo's cobblestone streets lined with ancestral houses.",
    region: "Luzon",
    province: "Ilocos Sur",
    latitude: 17.5755,
    longitude: 120.3869,
    categories: ["Historical", "City", "Food Trip"],
    tags: ["cultural", "heritage", "food", "photography"],
    budgetMin: 2000,
    budgetMax: 7000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [
      { name: "Viva Vigan Binatbatan Festival", month: 5, description: "Street dancing and cultural show celebrating Vigan heritage" },
    ],
  },
  {
    name: "Sagada",
    slug: "sagada",
    description:
      "A mountain town known for hanging coffins, stunning caves, and misty sunrise views at Kiltepan Peak. Sumaguing Cave is a must for spelunking enthusiasts.",
    region: "Luzon",
    province: "Mountain Province",
    latitude: 17.0833,
    longitude: 121.0053,
    categories: ["Mountain"],
    tags: ["hiking", "adventure", "cultural", "nature"],
    budgetMin: 2000,
    budgetMax: 6000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Cebu City",
    slug: "cebu-city",
    description:
      "The Queen City of the South — a bustling metropolis with rich history, incredible lechon, and vibrant nightlife. Visit Magellan's Cross, Basilica del Santo Niño, and Temple of Leah.",
    region: "Visayas",
    province: "Cebu",
    latitude: 10.3157,
    longitude: 123.8854,
    categories: ["City", "Historical", "Food Trip"],
    tags: ["food", "nightlife", "cultural", "heritage"],
    budgetMin: 2000,
    budgetMax: 10000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Year-round",
    festivals: [
      { name: "Sinulog", month: 1, description: "One of the largest festivals in the Philippines, honoring the Santo Niño" },
    ],
  },
  {
    name: "Puerto Princesa Underground River",
    slug: "puerto-princesa-underground-river",
    description:
      "A UNESCO World Heritage Site and one of the New 7 Wonders of Nature. Navigate through an 8.2-kilometer underground river with stunning limestone formations.",
    region: "Luzon",
    province: "Palawan",
    latitude: 10.1697,
    longitude: 118.9206,
    categories: ["Historical"],
    tags: ["nature", "adventure", "heritage", "unique"],
    budgetMin: 2500,
    budgetMax: 8000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Mayon Volcano",
    slug: "mayon-volcano",
    description:
      "The most perfectly shaped volcano cone in the world. ATV rides around the lava trails, hiking to the base camp, and breathtaking sunrise views define the Mayon experience.",
    region: "Luzon",
    province: "Albay",
    latitude: 13.2575,
    longitude: 123.6856,
    categories: ["Mountain"],
    tags: ["adventure", "photography", "nature", "hiking"],
    budgetMin: 2000,
    budgetMax: 7000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [
      { name: "Magayon Festival", month: 5, description: "Celebrates the beauty of Mayon Volcano and Bicolano culture" },
    ],
  },
  {
    name: "Camiguin",
    slug: "camiguin",
    description:
      "The Island Born of Fire — more volcanoes per square kilometer than any other island. Visit White Island sandbar, Katibawasan Falls, and the sunken cemetery.",
    region: "Mindanao",
    province: "Camiguin",
    latitude: 9.1525,
    longitude: 124.7217,
    categories: ["Beach", "Island Hopping", "Waterfall"],
    tags: ["nature", "adventure", "diving", "budget-friendly"],
    budgetMin: 1500,
    budgetMax: 5000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Mar-Jun)",
    festivals: [
      { name: "Lanzones Festival", month: 10, description: "Celebrates the bountiful lanzones harvest" },
    ],
  },
  {
    name: "Davao City",
    slug: "davao-city",
    description:
      "Home of the Philippine Eagle and the durian capital. Visit the Philippine Eagle Center, Eden Nature Park, and explore the bustling night markets.",
    region: "Mindanao",
    province: "Davao del Sur",
    latitude: 7.0707,
    longitude: 125.6087,
    categories: ["City", "Food Trip"],
    tags: ["food", "nature", "family-friendly", "cultural"],
    budgetMin: 2000,
    budgetMax: 8000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Year-round",
    festivals: [
      { name: "Kadayawan Festival", month: 8, description: "Thanksgiving celebration for the bountiful harvest" },
    ],
  },
  {
    name: "Batanes",
    slug: "batanes",
    description:
      "The northernmost province of the Philippines with rolling green hills, stone houses, and dramatic coastlines. Often compared to Scotland or New Zealand.",
    region: "Luzon",
    province: "Batanes",
    latitude: 20.4487,
    longitude: 121.9702,
    categories: ["Mountain"],
    tags: ["photography", "nature", "unique", "romantic"],
    budgetMin: 8000,
    budgetMax: 25000,
    budgetCategory: "Luxury",
    bestTimeToVisit: "Dry season (Mar-Jun)",
    festivals: [],
  },
  {
    name: "Apo Island",
    slug: "apo-island",
    description:
      "A world-class diving and snorkeling destination famous for its sea turtle sanctuary. Swim alongside hundreds of green sea turtles in crystal-clear waters.",
    region: "Visayas",
    province: "Negros Oriental",
    latitude: 9.0725,
    longitude: 123.2681,
    categories: ["Beach", "Island Hopping"],
    tags: ["diving", "snorkeling", "nature", "marine-life"],
    budgetMin: 1500,
    budgetMax: 5000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Hundred Islands",
    slug: "hundred-islands",
    description:
      "A national park with 124 islands and islets in the Lingayen Gulf. Island hop between Governor's Island, Quezon Island, and Children's Island for snorkeling and cliff jumping.",
    region: "Luzon",
    province: "Pangasinan",
    latitude: 16.2044,
    longitude: 119.9378,
    categories: ["Beach", "Island Hopping"],
    tags: ["family-friendly", "snorkeling", "adventure", "budget-friendly"],
    budgetMin: 1500,
    budgetMax: 5000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "BGC Taguig",
    slug: "bgc-taguig",
    description:
      "The modern face of Metro Manila — a walkable urban center with art murals, international dining, and nightlife. Visit Mind Museum, High Street, and the Venice Grand Canal Mall.",
    region: "NCR",
    province: "Metro Manila",
    latitude: 14.5506,
    longitude: 121.0475,
    categories: ["City", "Food Trip"],
    tags: ["nightlife", "food", "shopping", "urban"],
    budgetMin: 1500,
    budgetMax: 10000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Year-round",
    festivals: [],
  },
  {
    name: "Enchanted River",
    slug: "enchanted-river",
    description:
      "A deep spring river in Hinatuan with impossibly blue water. The source has never been fully explored. At noon, fish emerge for feeding time — a magical daily ritual.",
    region: "Mindanao",
    province: "Surigao del Sur",
    latitude: 8.5294,
    longitude: 126.2131,
    categories: ["Waterfall"],
    tags: ["nature", "unique", "swimming", "photography"],
    budgetMin: 1000,
    budgetMax: 3000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Year-round",
    festivals: [],
  },
  {
    name: "Kalanggaman Island",
    slug: "kalanggaman-island",
    description:
      "An uninhabited island with two pristine white sand bars stretching out on both ends. One of the most photogenic islands in the Philippines with crystal-clear waters.",
    region: "Visayas",
    province: "Leyte",
    latitude: 11.1333,
    longitude: 124.2667,
    categories: ["Beach", "Island Hopping"],
    tags: ["photography", "swimming", "nature", "budget-friendly"],
    budgetMin: 1500,
    budgetMax: 4000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Mar-Jun)",
    festivals: [],
  },
  {
    name: "Mount Pulag",
    slug: "mount-pulag",
    description:
      "The third highest peak in the Philippines, famous for its sea of clouds at sunrise. The Ambangeg trail is beginner-friendly, while the Akiki trail challenges experienced hikers.",
    region: "Luzon",
    province: "Benguet",
    latitude: 16.5875,
    longitude: 120.8878,
    categories: ["Mountain"],
    tags: ["hiking", "adventure", "photography", "nature"],
    budgetMin: 2500,
    budgetMax: 6000,
    budgetCategory: "Budget",
    bestTimeToVisit: "Dry season (Nov-May)",
    festivals: [],
  },
  {
    name: "Panglao Island",
    slug: "panglao-island",
    description:
      "Bohol's beach paradise with Alona Beach as the main hub. World-class diving at Balicasag Island, dolphin watching, and easy access to Chocolate Hills make it a complete destination.",
    region: "Visayas",
    province: "Bohol",
    latitude: 9.5617,
    longitude: 123.7633,
    categories: ["Beach", "Island Hopping"],
    tags: ["diving", "family-friendly", "romantic", "nature"],
    budgetMin: 2000,
    budgetMax: 10000,
    budgetCategory: "Mid-range",
    bestTimeToVisit: "Dry season (Mar-May)",
    festivals: [],
  },
] as const;

export const seed = internalMutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("destinations").take(1);
    if (existing.length > 0) {
      console.log("Destinations already seeded, skipping.");
      return;
    }

    for (const dest of destinations) {
      await ctx.db.insert("destinations", {
        name: dest.name,
        slug: dest.slug,
        description: dest.description,
        region: dest.region,
        province: dest.province,
        latitude: dest.latitude,
        longitude: dest.longitude,
        categories: [...dest.categories],
        tags: [...dest.tags],
        avgRating: 0,
        tipsCount: 0,
        bookmarksCount: 0,
        budgetMin: dest.budgetMin,
        budgetMax: dest.budgetMax,
        budgetCategory: dest.budgetCategory,
        bestTimeToVisit: dest.bestTimeToVisit,
        festivals: dest.festivals.map((f) => ({ ...f })),
        photosCount: 0,
        isPublished: true,
      });
    }

    console.log(`Seeded ${destinations.length} destinations.`);
  },
});
